version: '3'
services:
    php:
        container_name: symfony-backend-php-fpm
        hostname: php-fpm
        build:
            context: .
            dockerfile: ./Dockerfile_dev
            args:
                HOST_UID: $HOST_UID
                HOST_GID: $HOST_GID
        command: php-fpm
        user: $HOST_UID:$HOST_GID
        depends_on:
            - mysql
        volumes:
            - ./:/app:cached
            # Cannot use this because of the directory rights are forced for root user
            #- /app/var/
        environment:
            PHP_IDE_CONFIG: "serverName=app.localhost"

    nginx:
        container_name: symfony-backend-nginx
        hostname: nginx
        build:
            context: ./docker/nginx/
        depends_on:
            - php
        ports:
            - "8000:80"
        volumes:
            - ./:/app:cached
            # Cannot use this because of the directory rights are forced for root user
            #- /app/var/

    mysql:
        container_name: symfony-backend-mysql
        hostname: mysql
        build:
            context: ./docker/mysql/
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "33060:3306"
        volumes:
            - mysql:/var/lib/mysql

    dozzle:
        container_name: symfony-backend-dozzle
        hostname: dozzle
        image: amir20/dozzle
        ports:
            - "8080:8080"
        volumes:
            -  /var/run/docker.sock:/var/run/docker.sock
volumes:
    mysql:
