services:
    ProxyManager\Factory\AccessInterceptorValueHolderFactory:
        class: ProxyManager\Factory\AccessInterceptorValueHolderFactory

    doctrine.dbal.default_connection.stopwatch:
        class: Doctrine\DBAL\Connection
        decorates: doctrine.dbal.default_connection
        factory: [ '@App\Service\StopwatchDecorator', decorate ]
        arguments: [ '@doctrine.dbal.default_connection.stopwatch.inner' ]
